Itinerary.find(1).schedules.create!(
  [
    {
      schedule_date: Itinerary.find(1).departure_date,
      title: "関空から羽田経由でシドニーへ：機中泊",
      start_at: "15:00:00",
      end_at: "06:20:00",
      icon: "flight",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.tomorrow,
      title: "シドニー空港到着, 市内へ移動",
      start_at: "06:20:00",
      note: "国際線出口でガイドさんと合流",
      icon: "directions_car",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.tomorrow,
      title: "オペラハウス周辺観光",
      start_at: "11:00:00",
      end_at: "16:00:00",
      icon: "castle",
      place_id: "ChIJ3S-JXmauEmsRUcIaWtf4MzE",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.tomorrow,
      title: "ホテルにチェックイン",
      start_at: "17:00:00",
      icon: "hotel",
      place_id: "ChIJB_E7ITmuEmsRvpaogmLagvc",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.tomorrow,
      title: "ダーリングハーバーのステーキレストラン",
      start_at: "18:00:00",
      end_at: "20:00:00",
      icon: "restaurant",
      place_id: "ChIJvwSIiTiuEmsRBfZvg037JFM",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(2.days),
      title: "ブルーマウンテンズバスツアー",
      start_at: "7:00:00",
      end_at: "15:00:00",
      icon: "landscape",
      note: "7時にホテルロビー集合",
      place_id: "ChIJX3MkbG1CEmsRlh5d7yuNT7c",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(2.days),
      title: "ロックス周辺散策",
      start_at: "15:00:00",
      end_at: "18:30:00",
      icon: "castle",
      place_id: "ChIJs49dtkKuEmsRYM0yFmh9AQU",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(2.days),
      title: "サーキュラーキーで夕食",
      start_at: "18:30:00",
      end_at: "20:00:00",
      icon: "restaurant",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(3.days),
      title: "フェリーでタロンガ動物園へ移動",
      start_at: "09:30:00",
      end_at: "10:00:00",
      icon: "directions_bus",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(3.days),
      title: "タロンガ動物園",
      start_at: "10:00:00",
      end_at: "15:00:00",
      icon: "attractions",
      place_id: "ChIJq6qqWiSsEmsRJuIpepyEua4",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(3.days),
      title: "フェリーで市内へ",
      start_at: "15:00:00",
      end_at: "15:30:00",
      icon: "directions_bus",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(3.days),
      title: "シドニータワーの回転レストランで夕食",
      start_at: "19:00:00",
      end_at: "21:00:00",
      icon: "restaurant",
      place_id: "ChIJnzttoEGuEmsRjBEqGkOTGG8",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(4.days),
      title: "フェリーでワトソンズベイへ移動、周辺散策",
      start_at: "09:00:00",
      icon: "directions_bus",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(4.days),
      title: "フィッシュアンドチップスのランチ",
      start_at: "12:00:00",
      end_at: "13:00:00",
      icon: "restaurant",
      place_id: "ChIJAQCslmGsEmsR42HWIbRLn6k",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(4.days),
      title: "フェリーでシドニー市内へ戻る",
      start_at: "13:00:00",
      end_at: "14:00:00",
      icon: "directions_bus",
    },
    {
      schedule_date: Itinerary.find(1).departure_date.since(4.days),
      title: "市内観光（大聖堂など）",
      start_at: "14:00:00",
      end_at: "18:00:00",
      icon: "castle",
      place_id: "ChIJIfH_5hSuEmsR3jZ2qQd0ev4",
    },
    {
      schedule_date: Itinerary.find(1).return_date,
      title: "bills本店でブランチ",
      start_at: "9:00:00",
      icon: "restaurant",
      place_id: "ChIJTwxiPQ6uEmsR4k9fETyuHg8",
    },
    {
      schedule_date: Itinerary.find(1).return_date,
      title: "市内でショッピング",
      start_at: "13:00:00",
      end_at: "QVBでショッピング",
      icon: "shopping_cart",
      note: "頼まれていたKOKO BLACKのチョコレートを買うこと",
      place_id: "ChIJISz8NjyuEmsRFTQ9Iw7Ear8",
    },
    {
      schedule_date: Itinerary.find(1).return_date,
      title: "空港へ移動",
      start_at: "18:00:00",
      icon: "directions_car",
    },
    {
      schedule_date: Itinerary.find(1).return_date,
      title: "シドニーから関空へ",
      start_at: "21:45:00",
      end_at: "08:40:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(2).schedules.create!(
  [
    {
      schedule_date: Itinerary.find(2).departure_date,
      title: "新大阪から東京へ新幹線で移動",
      start_at: "18:00:00",
      end_at: "21:00:00",
      icon: "train",
    },
    {
      schedule_date: Itinerary.find(2).departure_date,
      title: "スパ&ホテル 舞浜ユーラシア チェックイン",
      start_at: "21:00:00",
      icon: "hotel",
      place_id: "ChIJu3aF__98GGARIcGzx-5SuBw",
    },
    {
      schedule_date: Itinerary.find(2).departure_date.tomorrow,
      title: "ホテルで朝食後、シーのゲート前へ移動",
      start_at: "06:30:00",
      icon: "directions_bus",
    },
    {
      schedule_date: Itinerary.find(2).departure_date.tomorrow,
      title: "東京ディズニーシー",
      start_at: "09:00:00",
      end_at: "21:00:00",
      icon: "attractions",
      place_id: "ChIJszdHEQN9GGARJS23SnAdR0E",
    },
    {
      schedule_date: Itinerary.find(2).departure_date.since(2.days),
      title: "ホテル出発、豊洲市場へ",
      start_at: "07:00:00",
      end_at: "08:00:00",
      icon: "train",
    },
    {
      schedule_date: Itinerary.find(2).departure_date.since(2.days),
      title: "寿司大で朝食、市場内見学",
      start_at: "08:00:00",
      end_at: "10:30:00",
      icon: "restaurant",
      place_id: "ChIJE6NVO9mLGGARUiKvcRmKzN4",
    },
    {
      schedule_date: Itinerary.find(2).departure_date.since(2.days),
      title: "チームラボプラネッツ TOKYO",
      start_at: "10:30:00",
      end_at: "12:30:00",
      icon: "local_activity",
      place_id: "ChIJSeco5wiJGGARItbTS8lQ5G0",
    },
    {
      schedule_date: Itinerary.find(2).departure_date.since(2.days),
      title: "東京駅周辺でランチと買い物",
      start_at: "12:30:00",
      end_at: "16:30:00",
      icon: "shopping_cart",
    },
    {
      schedule_date: Itinerary.find(2).departure_date.since(2.days),
      title: "ショコラティエ パレ ド オール 東京",
      start_at: "16:30:00",
      end_at: "17:30:00",
      icon: "local_cafe",
      place_id: "ChIJN4zgs_mLGGARXqUyHIyqsUs",
    },
    {
      schedule_date: Itinerary.find(2).departure_date.since(2.days),
      title: "東京駅から新大阪へ",
      start_at: "18:00:00",
      end_at: "21:00:00",
      icon: "train",
    },
  ]
)

Itinerary.find(3).schedules.create!(
  [
    {
      schedule_date: Itinerary.find(3).departure_date,
      title: "関空から宮古空港へ",
      start_at: "10:30:00",
      end_at: "13:15:00",
      icon: "flight",
    },
    {
      schedule_date: Itinerary.find(3).departure_date,
      title: "レンタカーを借りて伊良部島へ",
      start_at: "13:15:00",
      end_at: "14:00:00",
      icon: "directions_car",
      place_id: "ChIJLY3Tapes9TQRj4mcttbasrk",
    },
    {
      schedule_date: Itinerary.find(3).departure_date,
      title: "ブルータートル",
      start_at: "14:00:00",
      end_at: "14:30:00",
      icon: "local_cafe",
      place_id: "ChIJ4UHlGg2r9TQRbBVc5W_J1zI",
    },
    {
      schedule_date: Itinerary.find(3).departure_date,
      title: "移動",
      start_at: "14:30:00",
      end_at: "15:00:00",
      icon: "directions_car",
    },
    {
      schedule_date: Itinerary.find(3).departure_date,
      title: "通り池",
      start_at: "15:00:00",
      end_at: "15:30:00",
      icon: "landscape",
      place_id: "ChIJWxeNweWr9TQRs76MjAFnCjk"
    },
    {
      schedule_date: Itinerary.find(3).departure_date,
      title: "移動",
      start_at: "15:30:00",
      end_at: "16:00:00",
      icon: "directions_car",
    },
    {
      schedule_date: Itinerary.find(3).departure_date,
      title: "牧山展望台",
      start_at: "16:00:00",
      end_at: "16:30:00",
      icon: "landscape",
      place_id: "ChIJCd0T3pVT9DQRu4CXGt8dec0",
    },
    {
      schedule_date: Itinerary.find(3).departure_date,
      title: "宮古島に戻り、ホテルにチェックイン",
      start_at: "16:30:00",
      end_at: "17:30:00",
      icon: "hotel",
      place_id: "ChIJsXCir4lT9DQRLY76bIpgxLk",
    },
    {
      schedule_date: Itinerary.find(3).departure_date.tomorrow,
      title: "ダイブショップ集合",
      start_at: "08:00:00",
      icon: "directions_walk",
    },
    {
      schedule_date: Itinerary.find(3).departure_date.tomorrow,
      title: "ボートダイブ3本",
      start_at: "09:00:00",
      end_at: "16:00:00",
    },
    {
      schedule_date: Itinerary.find(3).return_date,
      title: "ホテル出発",
      start_at: "10:00:00",
      end_at: "10:30:00",
      icon: "directions_car",
    },
    {
      schedule_date: Itinerary.find(3).return_date,
      title: "砂山ビーチ",
      start_at: "10:30:00",
      end_at: "12:00:00",
      icon: "landscape",
      place_id: "ChIJ-zfBYbVT9DQR9rYeL_9KHpw",
    },
    {
      schedule_date: Itinerary.find(3).return_date,
      title: "移動",
      start_at: "12:00:00",
      end_at: "13:00:00",
      icon: "directions_car",
    },
    {
      schedule_date: Itinerary.find(3).return_date,
      title: "吉野海岸でシュノーケル",
      start_at: "13:00:00",
      end_at: "15:30:00",
      icon: "landscape",
      place_id: "ChIJfdMwqntZ9DQRH2MTmzeXr0g",
    },
    {
      schedule_date: Itinerary.find(3).return_date,
      title: "宮古空港へ向けて移動",
      start_at: "18:00:00",
      icon: "directions_car",
    },
    {
      schedule_date: Itinerary.find(3).return_date,
      title: "京都空港から関空へ",
      start_at: "20:10:00",
      end_at: "22:15:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(4).schedules.create!(
  [
    {
      schedule_date: Itinerary.find(4).departure_date,
      title: "関空から新千歳空港へ",
      start_at: "11:00:00",
      end_at: "13:00:00",
      icon: "flight",
    },
    {
      schedule_date: Itinerary.find(4).departure_date,
      title: "快速エアポートで札幌市内へ移動",
      start_at: "13:00:00",
      end_at: "14:00:00",
      icon: "train",
    },
    {
      schedule_date: Itinerary.find(4).departure_date,
      title: "ホテルチェックイン",
      start_at: "14:30:00",
      icon: "hotel",
      place_id: "ChIJVzEw7p8pC18RWbUUuZoPbVo",
    },
    {
      schedule_date: Itinerary.find(4).departure_date,
      title: "札幌市時計台、大通公園",
      start_at: "15:00:00",
      end_at: "17:00:00",
      icon: "castle",
      place_id: "ChIJR3JQJ3YpC18R680ES0qomxs",
    },
    {
      schedule_date: Itinerary.find(4).departure_date,
      title: "移動",
      start_at: "17:00:00",
      end_at: "18:00:00",
      icon: "train",
    },
    {
      schedule_date: Itinerary.find(4).departure_date,
      title: "藻岩山展望台で夜景観賞",
      start_at: "18:00:00",
      end_at: "19:00:00",
      icon: "landscape",
      place_id: "ChIJVxXPRfDVCl8REVDFQkZrz5o",
    },
    {
      schedule_date: Itinerary.find(4).departure_date,
      title: "炭火焼ジンギスカン 味の羊ヶ丘",
      start_at: "19:30:00",
      icon: "restaurant",
      place_id: "ChIJk4QcXEopC18Rj5z3M4MsIjQ",
    },
    {
      schedule_date: Itinerary.find(4).departure_date.tomorrow,
      title: "小樽駅へ移動",
      start_at: "07:00:00",
      end_at: "08:00:00",
      icon: "train",
    },
    {
      schedule_date: Itinerary.find(4).departure_date.tomorrow,
      title: "三角市場で海鮮丼",
      start_at: "08:00:00",
      end_at: "09:00:00",
      icon: "restaurant",
      place_id: "ChIJ52td3KzhCl8RckhF7-d8tv0",
    },
    {
      schedule_date: Itinerary.find(4).departure_date.tomorrow,
      title: "小樽運河周辺を散策",
      start_at: "09:00:00",
      end_at: "12:00:00",
      icon: "directions_walk",
      place_id: "ChIJzyHFIrPhCl8RKJu74CNakH8",
    },
    {
      schedule_date: Itinerary.find(4).departure_date.tomorrow,
      title: "小樽出抜小路でランチ",
      start_at: "12:00:00",
      icon: "restaurant",
      place_id: "ChIJces_OVbgCl8RVkZ6pp5MIuw",
    },
    {
      schedule_date: Itinerary.find(4).departure_date.tomorrow,
      title: "小樽オルゴール堂",
      start_at: "13:30:00",
      end_at: "15:00:00",
      icon: "castle",
      place_id: "ChIJB2IMXFrgCl8Rx-WS9YJOmbQ",
    },
    {
      schedule_date: Itinerary.find(4).departure_date.tomorrow,
      title: "ルタオ パトス",
      start_at: "15:00:00",
      end_at: "16:30:00",
      icon: "local_cafe",
      place_id: "ChIJIZMoGVDgCl8R8q1rwqlCkz0",
    },
    {
      schedule_date: Itinerary.find(4).departure_date.tomorrow,
      title: "札幌駅へ移動",
      start_at: "16:30:00",
      end_at: "17:30:00",
      icon: "train",
    },
    {
      schedule_date: Itinerary.find(4).departure_date.tomorrow,
      title: "ラーメン札幌一粒庵",
      start_at: "18:30:00",
      icon: "restaurant",
      place_id: "ChIJWbR8RnQpC18RD7V0WDDPGF4",
    },
    {
      schedule_date: Itinerary.find(4).return_date,
      title: "ホテル出発",
      start_at: "9:00:00",
      icon: "directions_bus",
    },
    {
      schedule_date: Itinerary.find(4).return_date,
      title: "北海道開拓の村",
      start_at: "10:30:00",
      end_at: "13:00:00",
      icon: "castle",
      place_id: "ChIJgeMaZessC18RlqucqXBeoKo",
    },
    {
      schedule_date: Itinerary.find(4).return_date,
      title: "一度ホテルに戻ってから空港へ移動",
      start_at: "13:00:00",
      end_at: "14:30:00",
      icon: "train",
    },
    {
      schedule_date: Itinerary.find(4).return_date,
      title: "新千歳空港到着、おみやげ購入",
      start_at: "14:30:00",
      icon: "shopping_cart",
    },
    {
      schedule_date: Itinerary.find(4).return_date,
      title: "新千歳空港からから関空へ",
      start_at: "17:00:00",
      end_at: "19:30:00",
      icon: "flight",
    },
  ]
)
