Itinerary.find(1).schedules.create!(
  [
    {
      date: Itinerary.find(1).departure_date,
      title: "関空から羽田経由でシドニーへ：機中泊",
      start_at: "15:00:00",
      end_at: "06:20:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(1).departure_date.tomorrow,
      title: "シドニー空港到着, 市内へ移動",
      start_at: "06:20:00",
      note: "国際線出口でガイドさんと合流",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(1).departure_date.tomorrow,
      title: "オペラハウス周辺観光",
      start_at: "11:00:00",
      end_at: "16:00:00",
      icon: "castle",
      place_id: "ChIJ3S-JXmauEmsRUcIaWtf4MzE",
    },
    {
      date: Itinerary.find(1).departure_date.tomorrow,
      title: "ホテルにチェックイン",
      start_at: "17:00:00",
      icon: "hotel",
      place_id: "ChIJB_E7ITmuEmsRvpaogmLagvc",
    },
    {
      date: Itinerary.find(1).departure_date.tomorrow,
      title: "ダーリングハーバーのステーキレストラン",
      start_at: "18:00:00",
      end_at: "20:00:00",
      icon: "restaurant",
      place_id: "ChIJvwSIiTiuEmsRBfZvg037JFM",
    },
    {
      date: Itinerary.find(1).departure_date.since(2.days),
      title: "ブルーマウンテンズバスツアー",
      start_at: "7:00:00",
      end_at: "15:00:00",
      icon: "landscape",
      note: "7時にホテルロビー集合",
      place_id: "ChIJX3MkbG1CEmsRlh5d7yuNT7c",
    },
    {
      date: Itinerary.find(1).departure_date.since(2.days),
      title: "ロックス周辺散策",
      start_at: "15:00:00",
      end_at: "18:30:00",
      icon: "castle",
      place_id: "ChIJs49dtkKuEmsRYM0yFmh9AQU",
    },
    {
      date: Itinerary.find(1).departure_date.since(2.days),
      title: "サーキュラーキーで夕食",
      start_at: "18:30:00",
      end_at: "20:00:00",
      icon: "restaurant",
    },
    {
      date: Itinerary.find(1).departure_date.since(3.days),
      title: "フェリーでタロンガ動物園へ移動",
      start_at: "09:30:00",
      end_at: "10:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(1).departure_date.since(3.days),
      title: "タロンガ動物園",
      start_at: "10:00:00",
      end_at: "15:00:00",
      icon: "attractions",
      place_id: "ChIJq6qqWiSsEmsRJuIpepyEua4",
    },
    {
      date: Itinerary.find(1).departure_date.since(3.days),
      title: "フェリーで市内へ",
      start_at: "15:00:00",
      end_at: "15:30:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(1).departure_date.since(3.days),
      title: "シドニータワーの回転レストランで夕食",
      start_at: "19:00:00",
      end_at: "21:00:00",
      icon: "restaurant",
      place_id: "ChIJnzttoEGuEmsRjBEqGkOTGG8",
    },
    {
      date: Itinerary.find(1).departure_date.since(4.days),
      title: "フェリーでワトソンズベイへ移動、周辺散策",
      start_at: "09:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(1).departure_date.since(4.days),
      title: "フィッシュアンドチップスのランチ",
      start_at: "12:00:00",
      end_at: "13:00:00",
      icon: "restaurant",
      place_id: "ChIJAQCslmGsEmsR42HWIbRLn6k",
    },
    {
      date: Itinerary.find(1).departure_date.since(4.days),
      title: "フェリーでシドニー市内へ戻る",
      start_at: "13:00:00",
      end_at: "14:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(1).departure_date.since(4.days),
      title: "市内観光（大聖堂など）",
      start_at: "14:00:00",
      end_at: "18:00:00",
      icon: "castle",
      place_id: "ChIJIfH_5hSuEmsR3jZ2qQd0ev4",
    },
    {
      date: Itinerary.find(1).return_date,
      title: "bills本店でブランチ",
      start_at: "9:00:00",
      icon: "restaurant",
      place_id: "ChIJTwxiPQ6uEmsR4k9fETyuHg8",
    },
    {
      date: Itinerary.find(1).return_date,
      title: "市内でショッピング",
      start_at: "13:00:00",
      end_at: "QVBでショッピング",
      icon: "shopping_cart",
      note: "頼まれていたKOKO BLACKのチョコレートを買うこと",
      place_id: "ChIJISz8NjyuEmsRFTQ9Iw7Ear8",
    },
    {
      date: Itinerary.find(1).return_date,
      title: "空港へ移動",
      start_at: "18:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(1).return_date,
      title: "シドニーから関空へ",
      start_at: "21:45:00",
      end_at: "08:40:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(2).schedules.create!(
  [
    {
      date: Itinerary.find(2).departure_date,
      title: "新大阪から東京へ新幹線で移動",
      start_at: "18:00:00",
      end_at: "21:00:00",
      icon: "train",
    },
    {
      date: Itinerary.find(2).departure_date,
      title: "スパ&ホテル 舞浜ユーラシア チェックイン",
      start_at: "21:00:00",
      icon: "hotel",
      place_id: "ChIJu3aF__98GGARIcGzx-5SuBw",
    },
    {
      date: Itinerary.find(2).departure_date.tomorrow,
      title: "ホテルで朝食後、シーのゲート前へ移動",
      start_at: "06:30:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(2).departure_date.tomorrow,
      title: "東京ディズニーシー",
      start_at: "09:00:00",
      end_at: "21:00:00",
      icon: "attractions",
      place_id: "ChIJszdHEQN9GGARJS23SnAdR0E",
    },
    {
      date: Itinerary.find(2).departure_date.since(2.days),
      title: "ホテル出発、豊洲市場へ",
      start_at: "07:00:00",
      end_at: "08:00:00",
      icon: "train",
    },
    {
      date: Itinerary.find(2).departure_date.since(2.days),
      title: "寿司大で朝食、市場内見学",
      start_at: "08:00:00",
      end_at: "10:30:00",
      icon: "restaurant",
      place_id: "ChIJE6NVO9mLGGARUiKvcRmKzN4",
    },
    {
      date: Itinerary.find(2).departure_date.since(2.days),
      title: "チームラボプラネッツ TOKYO",
      start_at: "10:30:00",
      end_at: "12:30:00",
      icon: "local_activity",
      place_id: "ChIJSeco5wiJGGARItbTS8lQ5G0",
    },
    {
      date: Itinerary.find(2).departure_date.since(2.days),
      title: "東京駅周辺でランチと買い物",
      start_at: "12:30:00",
      end_at: "16:30:00",
      icon: "shopping_cart",
    },
    {
      date: Itinerary.find(2).departure_date.since(2.days),
      title: "ショコラティエ パレ ド オール 東京",
      start_at: "16:30:00",
      end_at: "17:30:00",
      icon: "local_cafe",
      place_id: "ChIJN4zgs_mLGGARXqUyHIyqsUs",
    },
    {
      date: Itinerary.find(2).departure_date.since(2.days),
      title: "東京駅から新大阪へ",
      start_at: "18:00:00",
      end_at: "21:00:00",
      icon: "train",
    },
  ]
)

Itinerary.find(3).schedules.create!(
  [
    {
      date: Itinerary.find(3).departure_date,
      title: "関空から宮古空港へ",
      start_at: "10:30:00",
      end_at: "13:15:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(3).departure_date,
      title: "レンタカーを借りて伊良部島へ",
      start_at: "13:15:00",
      end_at: "14:00:00",
      icon: "directions_car",
      place_id: "ChIJLY3Tapes9TQRj4mcttbasrk",
    },
    {
      date: Itinerary.find(3).departure_date,
      title: "ブルータートル",
      start_at: "14:00:00",
      end_at: "14:30:00",
      icon: "local_cafe",
      place_id: "ChIJ4UHlGg2r9TQRbBVc5W_J1zI",
    },
    {
      date: Itinerary.find(3).departure_date,
      title: "移動",
      start_at: "14:30:00",
      end_at: "15:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(3).departure_date,
      title: "通り池",
      start_at: "15:00:00",
      end_at: "15:30:00",
      icon: "landscape",
      place_id: "ChIJWxeNweWr9TQRs76MjAFnCjk"
    },
    {
      date: Itinerary.find(3).departure_date,
      title: "移動",
      start_at: "15:30:00",
      end_at: "16:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(3).departure_date,
      title: "牧山展望台",
      start_at: "16:00:00",
      end_at: "16:30:00",
      icon: "landscape",
      place_id: "ChIJCd0T3pVT9DQRu4CXGt8dec0",
    },
    {
      date: Itinerary.find(3).departure_date,
      title: "宮古島に戻り、ホテルにチェックイン",
      start_at: "16:30:00",
      end_at: "17:30:00",
      icon: "hotel",
      place_id: "ChIJsXCir4lT9DQRLY76bIpgxLk",
    },
    {
      date: Itinerary.find(3).departure_date.tomorrow,
      title: "ダイブショップ集合",
      start_at: "08:00:00",
      icon: "directions_walk",
    },
    {
      date: Itinerary.find(3).departure_date.tomorrow,
      title: "ボートダイブ3本",
      start_at: "09:00:00",
      end_at: "16:00:00",
    },
    {
      date: Itinerary.find(3).return_date,
      title: "ホテル出発",
      start_at: "10:00:00",
      end_at: "10:30:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(3).return_date,
      title: "砂山ビーチ",
      start_at: "10:30:00",
      end_at: "12:00:00",
      icon: "landscape",
      place_id: "ChIJ-zfBYbVT9DQR9rYeL_9KHpw",
    },
    {
      date: Itinerary.find(3).return_date,
      title: "移動",
      start_at: "12:00:00",
      end_at: "13:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(3).return_date,
      title: "吉野海岸でシュノーケル",
      start_at: "13:00:00",
      end_at: "15:30:00",
      icon: "landscape",
      place_id: "ChIJfdMwqntZ9DQRH2MTmzeXr0g",
    },
    {
      date: Itinerary.find(3).return_date,
      title: "宮古空港へ向けて移動",
      start_at: "18:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(3).return_date,
      title: "京都空港から関空へ",
      start_at: "20:10:00",
      end_at: "22:15:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(4).schedules.create!(
  [
    {
      date: Itinerary.find(4).departure_date,
      title: "関空から新千歳空港へ",
      start_at: "11:00:00",
      end_at: "13:00:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(4).departure_date,
      title: "快速エアポートで札幌市内へ移動",
      start_at: "13:00:00",
      end_at: "14:00:00",
      icon: "train",
    },
    {
      date: Itinerary.find(4).departure_date,
      title: "ホテルチェックイン",
      start_at: "14:30:00",
      icon: "hotel",
      place_id: "ChIJVzEw7p8pC18RWbUUuZoPbVo",
    },
    {
      date: Itinerary.find(4).departure_date,
      title: "札幌市時計台、大通公園",
      start_at: "15:00:00",
      end_at: "17:00:00",
      icon: "castle",
      place_id: "ChIJR3JQJ3YpC18R680ES0qomxs",
    },
    {
      date: Itinerary.find(4).departure_date,
      title: "移動",
      start_at: "17:00:00",
      end_at: "18:00:00",
      icon: "train",
    },
    {
      date: Itinerary.find(4).departure_date,
      title: "藻岩山展望台で夜景観賞",
      start_at: "18:00:00",
      end_at: "19:00:00",
      icon: "landscape",
      place_id: "ChIJVxXPRfDVCl8REVDFQkZrz5o",
    },
    {
      date: Itinerary.find(4).departure_date,
      title: "炭火焼ジンギスカン 味の羊ヶ丘",
      start_at: "19:30:00",
      icon: "restaurant",
      place_id: "ChIJk4QcXEopC18Rj5z3M4MsIjQ",
    },
    {
      date: Itinerary.find(4).departure_date.tomorrow,
      title: "小樽駅へ移動",
      start_at: "07:00:00",
      end_at: "08:00:00",
      icon: "train",
    },
    {
      date: Itinerary.find(4).departure_date.tomorrow,
      title: "三角市場で海鮮丼",
      start_at: "08:00:00",
      end_at: "09:00:00",
      icon: "restaurant",
      place_id: "ChIJ52td3KzhCl8RckhF7-d8tv0",
    },
    {
      date: Itinerary.find(4).departure_date.tomorrow,
      title: "小樽運河周辺を散策",
      start_at: "09:00:00",
      end_at: "12:00:00",
      icon: "directions_walk",
      place_id: "ChIJzyHFIrPhCl8RKJu74CNakH8",
    },
    {
      date: Itinerary.find(4).departure_date.tomorrow,
      title: "小樽出抜小路でランチ",
      start_at: "12:00:00",
      icon: "restaurant",
      place_id: "ChIJces_OVbgCl8RVkZ6pp5MIuw",
    },
    {
      date: Itinerary.find(4).departure_date.tomorrow,
      title: "小樽オルゴール堂",
      start_at: "13:30:00",
      end_at: "15:00:00",
      icon: "castle",
      place_id: "ChIJB2IMXFrgCl8Rx-WS9YJOmbQ",
    },
    {
      date: Itinerary.find(4).departure_date.tomorrow,
      title: "ルタオ パトス",
      start_at: "15:00:00",
      end_at: "16:30:00",
      icon: "local_cafe",
      place_id: "ChIJIZMoGVDgCl8R8q1rwqlCkz0",
    },
    {
      date: Itinerary.find(4).departure_date.tomorrow,
      title: "札幌駅へ移動",
      start_at: "16:30:00",
      end_at: "17:30:00",
      icon: "train",
    },
    {
      date: Itinerary.find(4).departure_date.tomorrow,
      title: "ラーメン札幌一粒庵",
      start_at: "18:30:00",
      icon: "restaurant",
      place_id: "ChIJWbR8RnQpC18RD7V0WDDPGF4",
    },
    {
      date: Itinerary.find(4).return_date,
      title: "ホテル出発",
      start_at: "9:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(4).return_date,
      title: "北海道開拓の村",
      start_at: "10:30:00",
      end_at: "13:00:00",
      icon: "castle",
      place_id: "ChIJgeMaZessC18RlqucqXBeoKo",
    },
    {
      date: Itinerary.find(4).return_date,
      title: "一度ホテルに戻ってから空港へ移動",
      start_at: "13:00:00",
      end_at: "14:30:00",
      icon: "train",
    },
    {
      date: Itinerary.find(4).return_date,
      title: "新千歳空港到着、おみやげ購入",
      start_at: "14:30:00",
      icon: "shopping_cart",
    },
    {
      date: Itinerary.find(4).return_date,
      title: "新千歳空港からから関空へ",
      start_at: "17:00:00",
      end_at: "19:30:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(5).schedules.create!(
  [
    {
      date: Itinerary.find(5).departure_date,
      title: "関空〜ドバイ経由〜バルセロナへ",
      start_at: "23:30:00",
      end_at: "13:00:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(5).departure_date.tomorrow,
      title: "バルセロナ到着、市内へ移動",
      start_at: "14:00:00",
      end_at: "15:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(5).departure_date.tomorrow,
      title: "ホテルにチェックイン",
      start_at: "15:30:00",
      icon: "hotel",
    },
    {
      date: Itinerary.find(5).departure_date.since(2.days),
      title: "サグラダ・ファミリア",
      start_at: "09:00:00",
      end_at: "10:30:00",
      icon: "castle",
      place_id: "ChIJk_s92NyipBIRUMnDG8Kq2Js",
    },
    {
      date: Itinerary.find(5).departure_date.since(2.days),
      title: "グエル公園",
      start_at: "11:00:00",
      end_at: "12:30:00",
      icon: "castle",
      place_id: "ChIJq0HUUq6ipBIRWM6qGqALmok",
    },
    {
      date: Itinerary.find(5).departure_date.since(2.days),
      title: "パエリヤランチ",
      start_at: "13:00:00",
      end_at: "14:00:00",
      icon: "restaurant",
      place_id: "ChIJdUjd0vCipBIR0r-cyhOn98s",
    },
    {
      date: Itinerary.find(5).departure_date.since(2.days),
      title: "バスで市内観光（凱旋門〜カタルーニャ広場）",
      start_at: "14:00:00",
      end_at: "18:00:00",
      icon: "castle",
    },
    {
      date: Itinerary.find(5).departure_date.since(2.days),
      title: "フラメンコ鑑賞ディナー",
      start_at: "19:00:00",
      icon: "restaurant",
    },
    {
      date: Itinerary.find(5).departure_date.since(3.days),
      title: "ピカソ美術館",
      start_at: "09:00:00",
      end_at: "10:30:00",
      icon: "castle",
      place_id: "ChIJa-K8mf6ipBIRY8wAB3EeASc",
    },
    {
      date: Itinerary.find(5).departure_date.since(3.days),
      title: "カタルーニャ音楽堂",
      start_at: "11:00:00",
      end_at: "12:00:00",
      icon: "castle",
      place_id: "ChIJQQSrd_qipBIRQ2xzarVkqn8",
    },
    {
      date: Itinerary.find(5).departure_date.since(3.days),
      title: "ボケリア市場でランチ",
      start_at: "12:00:00",
      end_at: "14:00:00",
      icon: "restaurant",
      place_id: "ChIJAVoetfeipBIR1a1z3FTGCoY",
    },
    {
      date: Itinerary.find(5).departure_date.since(3.days),
      title: "カサ・バトリョとカサ・ミラ",
      start_at: "14:30:00",
      end_at: "17:30:00",
      icon: "castle",
      place_id: "ChIJYUFLSe2ipBIRD04uni940kA",
    },
    {
      date: Itinerary.find(5).departure_date.since(3.days),
      title: "バルで夕食",
      start_at: "18:00:00",
      icon: "restaurant",
      place_id: "ChIJ14DbPpKipBIROjfbj6-0FW0",
    },
    {
      date: Itinerary.find(5).departure_date.since(4.days),
      title: "バルセロナからグラナダへ移動",
      start_at: "11:00:00",
      end_at: "12:30:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(5).departure_date.since(4.days),
      title: "ヌエバ広場周辺散策",
      start_at: "14:00:00",
      end_at: "16:00:00",
      icon: "directions_walk",
      place_id: "Eh9QbC4gTnVldmEsIDE4MDEwIEdyYW5hZGEsIFNwYWluIi4qLAoUChIJ5-Y-z7j8cQ0RlXMS5LXhp-kSFAoSCX3CMi3m_HENEXINYNOd91iS"
    },
    {
      date: Itinerary.find(5).departure_date.since(4.days),
      title: "グラナダ大聖堂",
      start_at: "16:00:00",
      end_at: "17:00:00",
      icon: "castle",
      place_id: "ChIJqWuDsb_8cQ0RwlE55Uv7_nA"
    },
    {
      date: Itinerary.find(5).departure_date.since(5.days),
      title: "アルハンブラ宮殿",
      start_at: "09:00:00",
      end_at: "13:00:00",
      icon: "castle",
      place_id: "ChIJO7l_l7f8cQ0Rf6IhEu_RjYA"
    },
    {
      date: Itinerary.find(5).departure_date.since(5.days),
      title: "アルバイシン地区散策、サン・ニコラス広場",
      start_at: "14:00:00",
      end_at: "17:00:00",
      icon: "landscape",
      place_id: "ChIJlc_oycf8cQ0RmGSbIT5svlk"
    },
    {
      date: Itinerary.find(5).departure_date.since(5.days),
      title: "ヌエバ広場周辺のバルで夕食",
      start_at: "18:00:00",
      icon: "restaurant",
    },
    {
      date: Itinerary.find(5).departure_date.since(6.days),
      title: "ミハス一日観光ツアー",
      start_at: "09:00:00",
      end_at: "17:00:00",
      icon: "local_activity",
    },
    {
      date: Itinerary.find(5).return_date,
      title: "グラナダからバルセロナへ",
      start_at: "09:30:00",
      end_at: "11:00:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(5).return_date,
      title: "バルセロナ市内でショッピング",
      start_at: "12:00:00",
      end_at: "16:00:00",
      icon: "shopping_cart",
    },
    {
      date: Itinerary.find(5).return_date,
      title: "空港へ移動",
      start_at: "16:30:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(5).return_date,
      title: "グラナダ空港から関空へ向け出発",
      start_at: "20:30:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(6).schedules.create!(
  [
    {
      date: Itinerary.find(6).departure_date,
      title: "東京から新幹線で大阪へ",
      start_at: "17:00:00",
      end_at: "20:00:00",
      icon: "train",
    },
    {
      date: Itinerary.find(6).departure_date,
      title: "ホテル チェックイン",
      start_at: "20:00:00",
      icon: "hotel",
      place_id: "ChIJ5YYFTVLpAGARXjP1LqTiF8M",
    },
    {
      date: Itinerary.find(6).departure_date.tomorrow,
      title: "ユニバーサルスタジオジャパン",
      start_at: "09:00:00",
      end_at: "21:00:00",
      icon: "attractions",
      place_id: "ChIJXeLVg9DgAGARqlIyMCX-BTY",
    },
    {
      date: Itinerary.find(6).return_date,
      title: "ホテル出発、移動",
      start_at: "09:00:00",
      icon: "train",
    },
    {
      date: Itinerary.find(6).return_date,
      title: "大阪城公園",
      start_at: "10:00:00",
      end_at: "12:00:00",
      icon: "castle",
      place_id: "ChIJVVVld8ngAGARi9mE-a6e9mc",
    },
    {
      date: Itinerary.find(6).return_date,
      title: "JO-TERRACE OSAKAでランチ",
      start_at: "12:00:00",
      end_at: "13:30:00",
      icon: "restaurant",
      place_id: "ChIJ342Azc_gAGARbj2TEw7tkA4",
    },
    {
      date: Itinerary.find(6).return_date,
      title: "ホテル出発、移動",
      start_at: "13:30:00",
      icon: "train",
    },
    {
      date: Itinerary.find(6).return_date,
      title: "あべのハルカスの展望台へ",
      start_at: "14:00:00",
      end_at: "15:30:00",
      icon: "attractions",
      place_id: "ChIJ3eA7J_DdAGARil7_EwUaR_I",
    },
    {
      date: Itinerary.find(6).return_date,
      title: "通天閣",
      start_at: "16:00:00",
      end_at: "17:00:00",
      icon: "attractions",
      place_id: "ChIJ_0Lgd2DnAGARV0X03lbPy-U",
    },
    {
      date: Itinerary.find(6).return_date,
      title: "串かつだるま",
      start_at: "18:00:00",
      icon: "restaurant",
      place_id: "ChIJ5V4HCWDnAGARd6bIaaK91O4",
    },
    {
      date: Itinerary.find(6).return_date,
      title: "新大阪へ移動、東京へ",
      start_at: "20:00:00",
      end_at: "23:00:00",
      icon: "train",
    },
  ]
)

Itinerary.find(7).schedules.create!(
  [
    {
      date: Itinerary.find(7).departure_date,
      title: "新大阪から東京へ新幹線で移動",
      start_at: "06:30:00",
      end_at: "09:00:00",
      icon: "train",
    },
    {
      date: Itinerary.find(7).departure_date,
      title: "浅草寺",
      start_at: "09:30:00",
      end_at: "11:30:00",
      icon: "castle",
      place_id: "ChIJ8T1GpMGOGGARDYGSgpooDWw",
    },
    {
      date: Itinerary.find(7).departure_date,
      title: "浅草 牛かつでランチ",
      start_at: "12:00:00",
      end_at: "13:30:00",
      icon: "restaurant",
      place_id: "ChIJAQBs38aOGGARoOBOR4LoBdI",
    },
    {
      date: Itinerary.find(7).departure_date,
      title: "スカイツリー、ソラマチ観光",
      start_at: "14:00:00",
      end_at: "17:00:00",
      icon: "attractions",
      place_id: "ChIJ35ov0dCOGGARKvdDH7NPHX0",
    },
    {
      date: Itinerary.find(7).departure_date,
      title: "月島でもんじゃ",
      start_at: "18:00:00",
      icon: "restaurant",
    },
    {
      date: Itinerary.find(7).departure_date,
      title: "ホテルに到着",
      start_at: "20:00:00",
      icon: "hotel",
      place_id: "ChIJc8WesVmJGGARihndqe9RNv4",
    },
    {
      date: Itinerary.find(7).return_date,
      title: "上野動物園",
      start_at: "09:30:00",
      end_at: "12:00:00",
      icon: "attractions",
      place_id: "ChIJf2129yiMGGAR9I6Yoe-1uHY",
    },
    {
      date: Itinerary.find(7).return_date,
      title: "アメ横で食べ歩き",
      start_at: "12:30:00",
      end_at: "13:30:00",
      icon: "restaurant",
      place_id: "ChIJ1_WbPnSPGGARwKiIBvrR_dM",
    },
    {
      date: Itinerary.find(7).return_date,
      title: "移動",
      start_at: "13:30:00",
      end_at: "14:30:00",
      icon: "train",
    },
    {
      date: Itinerary.find(7).return_date,
      title: "明治神宮",
      start_at: "14:30:00",
      end_at: "17:30:00",
      icon: "castle",
      place_id: "ChIJ5SZMmreMGGARcz8QSTiJyo8",
    },
    {
      date: Itinerary.find(7).return_date,
      title: "東京駅に移動後、六厘舍のつけ麺",
      start_at: "18:00:00",
      icon: "restaurant",
      place_id: "ChIJtxODuv6LGGARnELlksWTmZo",
    },
    {
      date: Itinerary.find(7).return_date,
      title: "東京駅から新大阪へ",
      start_at: "19:30:00",
      end_at: "22:00:00",
      icon: "train",
    },
  ]
)

Itinerary.find(8).schedules.create!(
  [
    {
      date: Itinerary.find(8).departure_date,
      title: "関空からチャンギ空港へ",
      start_at: "10:10:00",
      end_at: "16:00:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(8).departure_date,
      title: "チャンギ空港から市内へ移動",
      start_at: "17:00:00",
      end_at: "17:30:00",
      icon: "train",
    },
    {
      date: Itinerary.find(8).departure_date,
      title: "マリーナ・ベイ・サンズ チェックイン",
      start_at: "18:00:00",
      icon: "hotel",
      place_id: "ChIJA5LATO4Z2jER111V-v6abAI",
    },
    {
      date: Itinerary.find(8).departure_date,
      title: "マカンストラ グラットンズ ベイ",
      start_at: "18:30:00",
      icon: "restaurant",
      place_id: "ChIJ7f__L20Z2jERt9btVig_DGw",
    },
    {
      date: Itinerary.find(8).departure_date,
      title: "『SPECTRA - 光と水のシンフォニー』鑑賞",
      start_at: "21:00:00",
      place_id: "ChIJJx8l4dkZ2jER4d43CclDwfs",
    },
    {
      date: Itinerary.find(8).departure_date.tomorrow,
      title: "マーライオン公園",
      start_at: "09:30:00",
      end_at: "10:30:00",
      icon: "castle",
      place_id: "ChIJBTYg1g4Z2jERp_MBbu5erWY",
    },
    {
      date: Itinerary.find(8).departure_date.tomorrow,
      title: "サンズ スカイパーク",
      start_at: "11:00:00",
      end_at: "12:00:00",
      icon: "attractions",
      place_id: "ChIJOeEf9S2vewIRM0B9a06CKwg",
    },
    {
      date: Itinerary.find(8).departure_date.tomorrow,
      title: "ガーデンズ バイ ザ ベイ",
      start_at: "12:30:00",
      end_at: "15:00:00",
      icon: "attractions",
      place_id: "ChIJMxZ-kwQZ2jERdsqftXeWCWI",
    },
    {
      date: Itinerary.find(8).departure_date.tomorrow,
      title: "TWG teaのアフタヌーンティー",
      start_at: "15:00:00",
      end_at: "17:00:00",
      icon: "local_cafe",
      place_id: "ChIJf_idiwYZ2jERma6qi0qljV4",
    },
    {
      date: Itinerary.find(8).departure_date.tomorrow,
      title: "オーチャード ロード周辺散策",
      start_at: "17:00:00",
      end_at: "19:00:00",
      icon: "directions_walk",
      place_id: "EhVPcmNoYXJkIFJkLCBTaW5nYXBvcmUiLiosChQKEgm7_uZIkRnaMRH69P43P_eZjhIUChIJdZOLiiMR2jERxPWrUs9peIg",
    },
    {
      date: Itinerary.find(8).departure_date.tomorrow,
      title: "ナイトサファリ",
      start_at: "19:30:00",
      end_at: "22:00:00",
      icon: "attractions",
      place_id: "ChIJ9xUuiNcT2jER49FS2OpE8W8",
    },
    {
      date: Itinerary.find(8).departure_date.since(2.days),
      title: "セントーサ ボードウォークでセントーサ島へ",
      start_at: "10:00:00",
      end_at: "10:30:00",
      icon: "directions_walk",
      place_id: "ChIJn9UClVcZ2jERVgJpLxTQaX8",
    },
    {
      date: Itinerary.find(8).departure_date.since(2.days),
      title: "シロソビーチ周辺散策",
      start_at: "10:30:00",
      end_at: "13:00:00",
      icon: "directions_walk",
    },
    {
      date: Itinerary.find(8).departure_date.since(2.days),
      title: "メガ・アドベンチャーパークなど",
      start_at: "13:00:00",
      end_at: "18:00:00",
      icon: "attractions",
      place_id: "ChIJpxs67_sb2jER1pJkEAHxc0Q",
    },
    {
      date: Itinerary.find(8).departure_date.since(2.days),
      title: "夕食",
      start_at: "18:00:00",
      icon: "restaurant",
      place_id: "ChIJ-eGhoVUZ2jER9N6KsweKuVY",
    },
    {
      date: Itinerary.find(8).departure_date.since(2.days),
      title: "ウイングス オブ タイム",
      start_at: "19:30:00",
      icon: "local_activity",
      place_id: "ChIJ3f__j_kb2jERYEEHaAfmcB8",
    },
    {
      date: Itinerary.find(8).return_date,
      title: "ホテルをチェックアウトして空港へ移動",
      start_at: "10:00:00",
      icon: "train",
    },
    {
      date: Itinerary.find(8).return_date,
      title: "チャンギ空港でおみやげ購入",
      start_at: "11:00:00",
      icon: "shopping_cart",
      place_id: "ChIJ483Qk9YX2jERA0VOQV7d1tY",
    },
    {
      date: Itinerary.find(8).return_date,
      title: "チャンギ空港から関空へ",
      start_at: "14:00:00",
      end_at: "21:40:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(9).schedules.create!(
  [
    {
      date: Itinerary.find(9).departure_date,
      title: "成田からイスタンブール空港へ",
      start_at: "10:15:00",
      end_at: "18:00:00",
      icon: "flight",
      note: "仮で入れました! 直行便はこれだけみたい。",
    },
    {
      date: Itinerary.find(9).return_date,
      title: "イスタンブール空港から成田へ",
      start_at: "02:40:00",
      end_at: "19:45:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(10).schedules.create!(
  [
    {
      date: Itinerary.find(10).departure_date,
      title: "関空からハノイへ",
      start_at: "10:30:00",
      end_at: "14:00:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(10).departure_date,
      title: "ノイバイ国際空港からエアポートバスで市内へ",
      start_at: "15:00:00",
      end_at: "16:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(10).departure_date,
      title: "ホテル チェックイン",
      start_at: "16:30:00",
      icon: "hotel",
      place_id: "ChIJgzIQXpWrNTEReyRCNrI39mE",
    },
    {
      date: Itinerary.find(10).departure_date,
      title: "ホエンキアム湖周辺散策、Cau Goで夕食",
      start_at: "16:30:00",
      end_at: "20:00:00",
      icon: "hotel",
      place_id: "ChIJ_wQ0jL-rNTERsNURCkQkU9E",
    },
    {
      date: Itinerary.find(10).departure_date.tomorrow,
      title: "ハロン湾日帰りクルーズツアーに参加",
      start_at: "08:00:00",
      end_at: "20:30:00",
      icon: "landscape",
      place_id: "ChIJh-6MUZZXSjER23hUyLywxlU",
    },
    {
      date: Itinerary.find(10).departure_date.since(2.days),
      title: "ホテルを出発、空港へ",
      start_at: "07:30:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(10).departure_date.since(2.days),
      title: "空路ホーチミンへ",
      start_at: "10:00:00",
      end_at: "12:00:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(10).departure_date.since(2.days),
      title: "市内へタクシー移動",
      start_at: "12:30:00",
      end_at: "13:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(10).departure_date.since(2.days),
      title: "Bánh Mì Huynh Hoaでバインミーを食べる",
      start_at: "13:30:00",
      end_at: "14:00:00",
      icon: "restaurant",
      place_id: "ChIJ9bBIK5ovdTERXOUNNEW8YGo",
    },
    {
      date: Itinerary.find(10).departure_date.since(2.days),
      title: "ドンコイ通り周辺を散策",
      start_at: "14:00:00",
      end_at: "18:00:00",
      icon: "directions_walk",
      place_id: "ChIJA11Q4FMvdTERE9FLbrEvi-g",
    },
    {
      date: Itinerary.find(10).departure_date.since(2.days),
      title: "ルーフトップバー",
      start_at: "19:00:00",
      icon: "restaurant",
      place_id: "ChIJO9BqXjYvdTERVrVlBcU1Ccc",
    },
    {
      date: Itinerary.find(10).departure_date.since(3.days),
      title: "サイゴン中央郵便局",
      start_at: "09:00:00",
      end_at: "11:00:00",
      icon: "castle",
      place_id: "ChIJRxocgI4udTERspsje3PV-LA",
    },
    {
      date: Itinerary.find(10).departure_date.since(3.days),
      title: "ベンタイン市場見学、ランチ",
      start_at: "11:00:00",
      end_at: "13:00:00",
      icon: "restaurant",
      place_id: "ChIJTeYpMT8vdTERMH8sUnkta40",
    },
    {
      date: Itinerary.find(10).departure_date.since(3.days),
      title: "おみやげなど市内で買い物",
      start_at: "13:00:00",
      end_at: "16:30:00",
      icon: "shopping_cart",
    },
    {
      date: Itinerary.find(10).departure_date.since(3.days),
      title: "ミウミウスパでマッサージ",
      start_at: "17:00:00",
      end_at: "19:00:00",
      place_id: "ChIJi94JKicvdTEReEzrQmAb48Y",
    },
    {
      date: Itinerary.find(10).departure_date.since(3.days),
      title: "空港へ移動",
      start_at: "20:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(10).return_date,
      title: "タンソンニャット空港から関空へ",
      start_at: "00:00:00",
      end_at: "07:00:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(11).schedules.create!(
  [
    {
      date: Itinerary.find(11).departure_date,
      title: "関空〜香港経由〜メルボルン空港",
      start_at: "18:05:00",
      end_at: "12:30:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(11).departure_date.tomorrow,
      title: "メルボルン空港から市内へ移動",
      start_at: "14:00:00",
      end_at: "14:30:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(11).departure_date.tomorrow,
      title: "ホテルにチェックイン",
      start_at: "14:30:00",
      icon: "hotel",
      place_id: "ChIJrfYQukhd1moRnmofhxAr0L0",
    },
    {
      date: Itinerary.find(11).departure_date.tomorrow,
      title: "Brother Baba Budanで一息",
      start_at: "15:00:00",
      end_at: "15:30:00",
      icon: "local_cafe",
      place_id: "ChIJ6VLiOLVC1moRUX_Qgb0CEyU",
    },
    {
      date: Itinerary.find(11).departure_date.tomorrow,
      title: "ビクトリア州立図書館",
      start_at: "16:00:00",
      end_at: "18:00:00",
      icon: "castle",
      place_id: "ChIJ6RxLlctC1moReA6DqUtnh_E",
    },
    {
      date: Itinerary.find(11).departure_date.tomorrow,
      title: "ギリシャ人街で夕食",
      start_at: "19:00:00",
      icon: "restaurant",
    },
    {
      date: Itinerary.find(11).departure_date.since(2.days),
      title: "グレートオーシャンロード1日観光ツアー",
      start_at: "08:00:00",
      end_at: "20:00:00",
      icon: "landscape",
      place_id: "ChIJTYfEb5Nv1GoRhAHDevGFv_Q",
    },
    {
      date: Itinerary.find(11).departure_date.since(3.days),
      title: "Hardware Sociétéでブランチ",
      start_at: "10:00:00",
      end_at: "12:00:00",
      icon: "restaurant",
      place_id: "ChIJ22hhMyVd1moRhP7ARjsyWc8",
    },
    {
      date: Itinerary.find(11).departure_date.since(3.days),
      title: "フィリップ島ペンギンパレードツアー",
      start_at: "13:00:00",
      end_at: "22:00:00",
      icon: "castle",
      place_id: "ChIJW7bw6GeV1WoRJ-q-NvGxZZw",
    },
    {
      date: Itinerary.find(11).departure_date.since(4.days),
      title: "クィーンヴィクトリア・マーケット",
      start_at: "09:00:00",
      end_at: "11:30:00",
      icon: "shopping_cart",
      place_id: "ChIJsVeQNzRd1moRUNQyBXZWBA8",
    },
    {
      date: Itinerary.find(11).departure_date.since(4.days),
      title: "Brunetti Oro Flinders Lane",
      start_at: "12:00:00",
      end_at: "13:30:00",
      icon: "restaurant",
      place_id: "ChIJg9OHO7RC1moR8LaOJz3PZok",
    },
    {
      date: Itinerary.find(11).departure_date.since(4.days),
      title: "王立展示館とカールトン庭園",
      start_at: "14:00:00",
      end_at: "16:30:00",
      icon: "castle",
      place_id: "ChIJcd7_l9lC1moRN3U9OQmxoEQ",
    },
    {
      date: Itinerary.find(11).departure_date.since(4.days),
      title: "ロイヤル・アーケード",
      start_at: "17:00:00",
      end_at: "19:00:00",
      icon: "shopping_cart",
      place_id: "ChIJeaaLoLVC1moRb4lG29-HxpI",
    },
    {
      date: Itinerary.find(11).departure_date.since(4.days),
      title: "Degraves Streetのレストランで夕食",
      start_at: "19:00:00",
      icon: "restaurant",
    },
    {
      date: Itinerary.find(11).return_date,
      title: "空港へ移動",
      start_at: "07:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(11).return_date,
      title: "タラマリン空港からホーチミン経由、関空へ",
      start_at: "10:00:00",
      end_at: "07:00:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(12).schedules.create!(
  [
    {
      date: Itinerary.find(12).departure_date,
      title: "関空から那覇空港へ",
      start_at: "07:45:00",
      end_at: "10:15:00",
      icon: "flight",
      note: "6:15に空港駅の改札前集合"
    },
    {
      date: Itinerary.find(12).departure_date,
      title: "ゆいレールで市内へ移動",
      start_at: "11:00:00",
      end_at: "11:30:00",
      icon: "train",
    },
    {
      date: Itinerary.find(12).departure_date,
      title: "ホテルチェックイン、周辺でランチ",
      start_at: "12:00:00",
      end_at: "13:00:00",
      icon: "hotel",
      place_id: "ChIJgbtSqHlp5TQRQhSW_XAig6w",
    },
    {
      date: Itinerary.find(12).departure_date,
      title: "首里城",
      start_at: "13:30:00",
      end_at: "15:00:00",
      icon: "castle",
      place_id: "ChIJZ9v0bP5r5TQRi0-esrqficA",
    },
    {
      date: Itinerary.find(12).departure_date,
      title: "国際通り周辺散策",
      start_at: "15:30:00",
      end_at: "18:00:00",
      icon: "directions_walk",
    },
    {
      date: Itinerary.find(12).departure_date,
      title: "国際通り屋台村で夕食",
      start_at: "18:30:00",
      icon: "restaurant",
      place_id: "ChIJp_frzRdp5TQRM21nQKlERjg",
    },
    {
      date: Itinerary.find(12).departure_date.tomorrow,
      title: "レンタカーで名護方面へ",
      start_at: "07:00:00",
      end_at: "09:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(12).departure_date.tomorrow,
      title: "美ら海水族館",
      start_at: "09:30:00",
      end_at: "11:30:00",
      icon: "attractions",
      place_id: "ChIJPZ5hUjH65DQR_p_dD3CmCOo",
    },
    {
      date: Itinerary.find(12).departure_date.tomorrow,
      title: "今帰仁城跡",
      start_at: "12:00:00",
      end_at: "13:00:00",
      icon: "castle",
      place_id: "ChIJk_KWO7b55DQRF6wOVeWpIDE",
    },
    {
      date: Itinerary.find(12).departure_date.tomorrow,
      title: "古宇利大橋からハートロックへ",
      start_at: "13:30:00",
      end_at: "14:30:00",
      icon: "landscape",
      place_id: "ChIJf3Y9SjJY5DQRIZUnKV_U1Hg"
    },
    {
      date: Itinerary.find(12).departure_date.tomorrow,
      title: "移動",
      start_at: "14:30:00",
      end_at: "15:30:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(12).departure_date.tomorrow,
      title: "ブセナ海中公園",
      start_at: "15:30:00",
      end_at: "16:30:00",
      icon: "landscape",
      place_id: "ChIJcTekltIB5TQRZBundTA3oqs",
    },
    {
      date: Itinerary.find(12).departure_date.tomorrow,
      title: "恩納村方面へ",
      start_at: "16:30:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(12).departure_date.tomorrow,
      title: "恩納村のホテル到着",
      start_at: "17:00:00",
      icon: "hotel",
      place_id: "ChIJPTpipQoQ5TQRsw5dJ7VZL6U",
    },
    {
      date: Itinerary.find(12).return_date,
      title: "青の洞窟シュノーケル",
      start_at: "07:00:00",
      end_at: "10:00:00",
      icon: "local_activity",
      note: "7時にホテルロビー迎え、水着着用しておくこと",
      place_id: "ChIJFSBnObgb5TQRQA1ByAocZog",
    },
    {
      date: Itinerary.find(12).return_date,
      title: "移動",
      start_at: "10:30:00",
      end_at: "11:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(12).return_date,
      title: "アラハビーチでのんびり",
      start_at: "11:00:00",
      end_at: "15:00:00",
      icon: "landscape",
      place_id: "ChIJJdFU6tsT5TQRFtGMxK9GlzU",
    },
    {
      date: Itinerary.find(12).return_date,
      title: "那覇空港へ向け移動、途中で沖縄そばのお店へ",
      start_at: "15:30:00",
      icon: "directions_car",
      place_id: "ChIJD1vXUUJt5TQRfo8lA2NxrdE",
      note: "レンタカーは18:00まで"
    },
    {
      date: Itinerary.find(12).return_date,
      title: "那覇空港から関空へ",
      start_at: "19:00:00",
      end_at: "21:00:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(13).schedules.create!(
  [
    {
      date: Itinerary.find(13).departure_date,
      title: "関空からバンコク・スワンナプーム国際空港へ",
      start_at: "10:00:00",
      end_at: "14:30:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(13).departure_date,
      title: "空港から市内へタクシーで移動",
      start_at: "15:30:00",
      end_at: "16:30:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(13).departure_date,
      title: "ジャスミン 59 ホテル チェックイン",
      start_at: "17:00:00",
      icon: "hotel",
      place_id: "ChIJKwG7UOWf4jAR0VlUeXp8r8o",
    },
    {
      date: Itinerary.find(13).departure_date,
      title: "屋台街で夕食",
      start_at: "18:00:00",
      icon: "restaurant",
    },
    {
      date: Itinerary.find(13).departure_date.tomorrow,
      title: "アユタヤ遺跡までロットゥーで移動",
      start_at: "08:30:00",
      end_at: "10:00:00",
      icon: "directions_bus",
      note: "チャットチャックでチケット購入 70THB",
      place_id: "ChIJ3QVwhWic4jARmaIavJZIWyY",
    },
    {
      date: Itinerary.find(13).departure_date.tomorrow,
      title: "アユタヤ遺跡",
      start_at: "10:30:00",
      end_at: "16:30:00",
      icon: "castle",
      place_id: "ChIJ2ZdRNT904jARefHtt0HLuUk",
    },
    {
      date: Itinerary.find(13).departure_date.tomorrow,
      title: "バンコクへ戻る",
      start_at: "16:30:00",
      end_at: "18:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(13).departure_date.since(2.days),
      title: "長距離バスでパタヤへ",
      start_at: "07:00:00",
      end_at: "09:30:00",
      icon: "directions_bus",
      place_id: "ChIJ9aDDbKWf4jARdYpBcUyeMdc",
    },
    {
      date: Itinerary.find(13).departure_date.since(2.days),
      title: "パタヤビーチでジェットスキーとパラセーリング",
      start_at: "10:00:00",
      end_at: "15:00:00",
      icon: "local_activity",
    },
    {
      date: Itinerary.find(13).departure_date.since(2.days),
      title: "パタヤヒルの展望台",
      start_at: "15:00:00",
      end_at: "17:00:00",
      icon: "landscape",
      place_id: "ChIJ6w0EqmeWAjERaKcDGOn1nQQ",
    },
    {
      date: Itinerary.find(13).departure_date.since(2.days),
      title: "長距離バスでバンコクへ戻る",
      start_at: "17:00:00",
      end_at: "19:30:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(13).departure_date.since(3.days),
      title: "長距離バスでバンコクへ戻る",
      start_at: "17:00:00",
      end_at: "19:30:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(13).departure_date.since(3.days),
      title: "ホテルを出発してサナームチャイ駅へ",
      start_at: "09:00:00",
      icon: "train",
      note: "地下鉄ブルーライン",
    },
    {
      date: Itinerary.find(13).departure_date.since(3.days),
      title: "ワット・プラケオ",
      start_at: "10:30:00",
      end_at: "11:00:00",
      icon: "castle",
      place_id: "ChIJ5Wl37g6Z4jARiP4itarBPDQ",
    },
    {
      date: Itinerary.find(13).departure_date.since(3.days),
      title: "ワット・ポー",
      start_at: "11:00:00",
      end_at: "12:00:00",
      icon: "castle",
      place_id: "ChIJgcxFcQWZ4jARLsIR9Qia9H0",
    },
    {
      date: Itinerary.find(13).departure_date.since(3.days),
      title: "ホームカフェ ター ティアン",
      start_at: "12:00:00",
      end_at: "13:00:00",
      icon: "restaurant",
      place_id: "ChIJ6aLoxQWZ4jARd7FjOaPiQ08",
    },
    {
      date: Itinerary.find(13).departure_date.since(3.days),
      title: "ワット・アルン",
      start_at: "13:30:00",
      end_at: "15:00:00",
      icon: "castle",
      place_id: "ChIJaSv_6gaZ4jARnbiUVn6Z_YY",
    },
    {
      date: Itinerary.find(13).departure_date.since(3.days),
      title: "ボートで移動",
      start_at: "15:00:00",
      end_at: "16:00:00",
      icon: "directions_bus",
      place_id: "ChIJXQta9QaZ4jARBE_MxUDC4HM",
    },
    {
      date: Itinerary.find(13).departure_date.since(3.days),
      title: "カオサン通りを散策",
      start_at: "16:00:00",
      end_at: "18:00:00",
      icon: "directions_walk",
    },
    {
      date: Itinerary.find(13).departure_date.since(3.days),
      title: "ナイトマーケット",
      start_at: "18:00:00",
      icon: "restaurant",
      place_id: "ChIJXWLwuIie4jARHflkjQu6MCw",
    },
    {
      date: Itinerary.find(13).return_date,
      title: "ホテルをチェックアウトして空港へ移動",
      start_at: "09:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(13).return_date,
      title: "スワンナプーム国際空港から関空へ",
      start_at: "12:00:00",
      end_at: "19:40:00",
      icon: "flight",
    },
  ]
)

Itinerary.find(14).schedules.create!(
  [
    {
      date: Itinerary.find(14).departure_date,
      title: "伊丹から羽田経由、旭川空港へ",
      start_at: "08:30:00",
      end_at: "12:30:00",
      icon: "flight",
    },
    {
      date: Itinerary.find(14).departure_date,
      title: "移動",
      start_at: "13:00:00",
      end_at: "14:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(14).departure_date,
      title: "旭山動物園",
      start_at: "14:00:00",
      end_at: "16:00:00",
      icon: "attractions",
      place_id: "ChIJyyPgtczgDF8R01OoHb3cJcg",
    },
    {
      date: Itinerary.find(14).departure_date,
      title: "ホテル到着 JRイン旭川",
      start_at: "17:00:00",
      icon: "hotel",
      place_id: "ChIJOdlckhDmDF8RBCotONjS4B4",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "レンタカーで美瑛方面へ",
      start_at: "08:00:00",
      end_at: "09:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "新栄の丘展望公園",
      start_at: "09:00:00",
      end_at: "09:30:00",
      icon: "landscape",
      place_id: "ChIJN62Fu5jIDF8RIHsgUAlAs14",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "移動",
      start_at: "09:30:00",
      end_at: "10:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "青い池",
      start_at: "10:00:00",
      end_at: "11:30:00",
      icon: "landscape",
      place_id: "ChIJO9A234XMDF8RJtGsT6ZhCrU",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "移動",
      start_at: "11:30:00",
      end_at: "12:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "四季彩の丘",
      start_at: "12:00:00",
      end_at: "14:00:00",
      icon: "landscape",
      place_id: "ChIJDeIPuVXIDF8RPhiBRw83_ag",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "移動",
      start_at: "14:00:00",
      end_at: "14:30:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "ファーム富田",
      start_at: "14:30:00",
      end_at: "16:30:00",
      icon: "landscape",
      place_id: "ChIJdzcW1F2zDF8Rkm1ghwLPbbc",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "移動",
      start_at: "16:30:00",
      end_at: "17:00:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "フラノマルシェ",
      start_at: "17:00:00",
      end_at: "18:30:00",
      icon: "shopping_cart",
      place_id: "ChIJdzcW1F2zDF8Rkm1ghwLPbbc",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "旭川方面へ移動",
      start_at: "18:30:00",
      end_at: "19:30:00",
      icon: "directions_car",
    },
    {
      date: Itinerary.find(14).departure_date.tomorrow,
      title: "成吉思汗 大黒屋 五丁目店",
      start_at: "19:30:00",
      icon: "restaurant",
      place_id: "ChIJRf7PMgzmDF8Rm_3HyHkvjn0",
    },
    {
      date: Itinerary.find(14).return_date,
      title: "ホテル出発、神居古潭へ",
      start_at: "09:30:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(14).return_date,
      title: "神居古潭",
      start_at: "10:00:00",
      end_at: "11:30:00",
      icon: "landscape",
      place_id: "ChIJY8A47hPsDF8RaEy5NMzWSSw",
    },
    {
      date: Itinerary.find(14).return_date,
      title: "旭川市方面へ戻る",
      start_at: "11:30:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(14).return_date,
      title: "旭川らぅめん青葉 本店",
      start_at: "12:00:00",
      end_at: "13:00:00",
      icon: "restaurant",
      place_id: "ChIJYaeSJBLmDF8RUFu2RcwxelA",
    },
    {
      date: Itinerary.find(14).return_date,
      title: "空港へ移動",
      start_at: "14:00:00",
      end_at: "15:00:00",
      icon: "directions_bus",
    },
    {
      date: Itinerary.find(14).return_date,
      title: "旭川空港からから伊丹へ",
      start_at: "16:20:00",
      end_at: "20:0:00",
      icon: "flight",
    },
  ]
)
