default: &default
  adapter: postgresql
  encoding: unicode
  collation: utf8_general_ci
  host: <%= ENV['RDS_HOSTNAME'] || 'localhost' %>
  username: <%= ENV['RDS_USERNAME'] || 'bestrip' %>
  password: <%= ENV['RDS_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bestrip_development

test:
  <<: *default
  database: bestrip_test

production:
  <<: *default
  database: bestrip_production
  # password: <%= ENV["BESTRIP_DATABASE_PASSWORD"] %>
