name: EC2 deploy

on:
  push:
    branches:
      - 'develop/09-refactoring'

jobs:
  rubocop:
    uses: ./.github/workflows/rubocop.yml

  rspec:
    needs: rubocop
    uses: ./.github/workflows/rspec.yml
    secrets: inherit

  deploy:
    needs: rspec
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.GIT_PRIVATE_KEY }}
          host: ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.EC2_USER_NAME }}
          port: 22
          script: |
            cd /var/www/bestrip
            git pull origin develop/09-refactoring
            ~/.rbenv/shims/bundle install
            ~/.rbenv/shims/bundle exec rails db:migrate RAILS_ENV=production
            ~/.rbenv/shims/bundle exec rails db:seeds
            ~/.rbenv/shims/bundle exec rails assets:precompile RAILS_ENV=production
            sudo systemctl restart nginx
            kill $(cat tmp/server.pid)
            ~/.rbenv/shims/bundle exec rails s -e production
